
#{% set data = load_setup_py_data() %}

package:
  name: epidope
  
  version: 0.1
#  version: {{ data['version'] }}

source:
  path: ../

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  #  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt
  #  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .
  #  to limit to Python 3.6 and newer
  skip: True  # [py<36]


requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python ==3.7.6
    - tensorflow ==1.13.1
    - bokeh ==1.4.0
    - numpy ==1.17.4
    - scikit-learn ==0.22
    - keras ==2.3.1
    - pytorch ==1.3.1
    - libwebp ==1.0.2


about:
  home: https://github.com/flomock/EpiDope
  summary: Prediction of B-cell epitopes from amino acid sequences using deep neural networks. 
  license: MIT
#  license: {{ setup_py.get('license') }}
  license_file: LICENSE
